### ISSUE TITLE
ODBC.jl incompatible with Julia 0.3.11

### ISSUE THREAD

**Issue by bmharsha** [JuliaDB/ODBC.jl#107]
Latest commits have made ODBC.jl incompatible with Julia Version 0.3.11

``` julia> using ODBC``` will result in following error 
```
ERROR: type: instantiate_type: expected TypeConstructor, got Function
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /home/julia/.julia/v0.3/ODBC/src/ODBC_API.jl, in expression starting on line 174
while loading /home/julia/.julia/v0.3/ODBC/src/ODBC.jl, in expression starting on line 16
```

Inspite of the error, ODBC.jl exports most functions and variables onto the Workspace, I tried connecting to MySQL database using following statement 

``` con = ODBC.connect("MySQl_DSN")``` , even this statement resulted in an error hence making ODBC.jl unusable on Version 0.3.11
```
ERROR: connect: no such file or directory (ENOENT)
 in wait at ./task.jl:284
 in wait at ./task.jl:194
 in stream_wait at ./stream.jl:263
 in wait_connected at stream.jl:301
 in connect at stream.jl:917
```

**Comment by quinnj** [comment]
I'm not seeing this same error using Julia 0.3.11 and current ODBC master.

**Comment by bmharsha** [comment]
This issue was fixed by this pull request : https://github.com/JuliaDB/ODBC.jl/pull/110 , even Travis is testing on Julia 0.3 : https://travis-ci.org/JuliaDB/ODBC.jl/jobs/100279263 , ODBC.jl is passing all the tests without any issues, this issue can be closed.

**Comment by quinnj** [comment]
Great!
