### ISSUE TITLE
Failing on 0.4 master (#84) - Solution incomplete (Mac OS X)

### ISSUE THREAD

**Issue by cgoodhart** [JuliaDB/ODBC.jl#109]
SUBJ: CLOSED ISSUE #84 (ODBC fail) on 0.4 MASTER - SOLUTION INCOMPLETE (MAC OS X)
**Updated - to include Ivo's comments & corrections below**

Believe this has a simple fix.

Issue #84 indeed seems to be fixed on github within the ODBC package, but the corrected code does not install with 0.4.1:
https://github.com/JuliaDB/ODBC.jl/issues/84

The problem appears to be in the url stored under METADATA for ODBC when Julia 0.4.1 is installed (specifically for OS X - I did not check other platforms, but am crossing fingers with my Windows installation that this doesn't recur). After installation, the locally-installed file:

~/.julia/v0.4/METADATA/ODBC/url

reads:

git://github.com/quinnj/ODBC.jl.git

which matches the METADATA source on:

https://github.com/JuliaLang/METADATA.jl

EXCEPT: that is not where the corrected .jl files reside; instead, they reside at:

https://github.com/JuliaDB/ODBC.jl

I'm in no way savvy enough to be certain, but suspect if the url file in METADATA were corrected to git://github.com/JuliaDB/ODBC.jl.git, the problem would not recur on a new install of Julia 0.4.1.

-----DETAILS TO REPRODUCE OR VALIDATE-----
Steps:
0. Remove any previous Julia versions per instructions at julialang.org
1. Download Julia v0.4.1 for Mac OS X at: https://s3.amazonaws.com/julialang/bin/osx/x64/0.4/julia-0.4.1-osx10.7+.dmg
(linked from julialang.org/downloads)
2. Install and start Julia
3. Pkg.init()
4. Pkg.add("ODBC")
5. using ODBC
Expected result: julia prompt
Actual result:   https://github.com/JuliaDB/ODBC.jl/issues/84

Workaround:
1. Repeat steps 1-4 above
2. With browser, navigate to https://github.com/JuliaDB/ODBC.jl
3. Locally, navigate to install dir or ~/.julia/v0.4/ODBC
4. Replace local file contents with contents at https://github.com/JuliaDB/ODBC.jl
5. Remove ~/.julia/v0.4/ODBC/.git/ directory (may not be needed but that's what I did)
6. Pkg.build("ODBC")
7. using ODBC
Expected result: Can establish db connection, query successfully, etc
Actual result:   OK

System: OS X v10.11.1, iMac 27" late 2013
Processor: 3.2GHz intel core i5
Term: bash / target env: Jupyter
Immediate use: large scale LP with JuMP/Clp reading/writing data from/to Postgres.

**Comment by cgoodhart** [comment]
Probably should've suggested an alternate url content of "git://" vs "https://"...

**Comment by cgoodhart** [comment]
Should mention: changing the url locally results in chaos, with Julia reporting that METADATA is out of date, and Pkg.update() subsequently failing.

**Comment by Ivo-Balbaert** [comment]
Thanks very much! This worked for me on Windows 10 64 bit with Julia 0.4.1 (step 5 is Pkg.build("ODBC")).
I sure hope this will be fixed soon so that new ODBC users can follow the usual procedure when adding ODBC.

**Comment by cgoodhart** [comment]
Thank you - I'm new to this forum and finally figured out the little pencil icon lets me edit, so I updated the steps above incorporating your correction. I share your hope.

**Comment by cgoodhart** [comment]
@bmharsha - would you be able to revisit your comment re: "this is fixed" on issue #84 and help us get this fixed in its entirety?

**Comment by bmharsha** [comment]
@nkottary @viral Can we send a pull request to Metadata.jl ? The version in Metadata is not compatible with 0.4 , hence many users are facing issues when they do a ```Pkg.add("ODBC")``` on Julia version 0.4 (and above)

@cgoodhart As a simple work around, you can use following statement instead of ```Pkg.add("ODBC")```
```
Pkg.clone("https://github.com/JuliaDB/ODBC.jl.git")
```

**Comment by ViralBShah** [comment]
Yes please, let's tag. It is long overdue.

**Comment by nkottary** [comment]
Pull request can be found [here](https://github.com/JuliaLang/METADATA.jl/pull/4154).

**Comment by cgoodhart** [comment]
Would love to close this when actually corrected - currently looking at:
http://screencast.com/t/SAFRz0cwty

**Comment by ViralBShah** [comment]
@quinnj said he has a new overhaul branch that he will be merging shortly.

**Comment by bmharsha** [comment]
@cgoodhart Metadata now has the latest version of ODBC.jl , this version is compatible with Julia 0.4.2 ,  can you please cross verify and close this issue?
