### ISSUE TITLE
Error on connecting more than one DSN in the same program.

### ISSUE THREAD

**Issue by nkottary** [JuliaDB/ODBC.jl#121]
This issue is in the latest checkout of jq/remodel branch.

I have setup MySQL and PostgreSQL database servers and I'm able to connect to each of them in separate programs.  However, I encounter this error when trying to open both connections in the same program:

```julia
julia> hndl = ODBC.DSN("ODBC-MySQL")
ODBC.DSN(ODBC-MySQL)

julia> pg_hndl = ODBC.DSN("postgres", "postgres", "postgres")
[ODBC] IM002: [unixODBC][Driver Manager]Data source name not found, and no default driver specified
ERROR: ODBC.ODBCError("ODBC.API.SQLDriverConnect(dbc,window_handle,conn_string,out_conn.ptr,BUFLEN,out_buff,driver_prompt) failed; return code: -1 => SQL_ERROR")
 [inlined code] from /home/Nishanth/.julia/v0.4/ODBC/src/ODBC.jl:35
 in ODBCDriverConnect! at /home/Nishanth/.julia/v0.4/ODBC/src/backend.jl:13
 in DSN at /home/Nishanth/.julia/v0.4/ODBC/src/ODBC.jl:91

julia>
```

This bug doesn't exist on `master`.

The same error is thrown when using a different Oracle DB dsn.  Reversing  the order of connection i.e., calling `ODBC.DSN("postgres", ...)` first and then `ODBC.DSN("ODBC-MySQL")` results in the same error.

Also there is a bug in `ODBC.disconnect!`:

```julia
julia> ODBC.disconnect!(hndl)
ERROR: UndefVarError: SQLDisconnect not defined
 in disconnect! at /home/Nishanth/.julia/v0.4/ODBC/src/ODBC.jl:100
```

**Comment by quinnj** [comment]
Will be fixed by e21cbbc248dacf05ac16739338f0a9817c870ab3 and 667e4263272b3a46087d60720fc3b3840e490687

**Comment by quinnj** [comment]
fixed

**Comment by nkottary** [comment]
Thanks! :+1:
