### ISSUE TITLE
Error converting DataTable to DataFrame

### ISSUE THREAD

**Issue by awang94** [JuliaDB/ODBC.jl#125]
I'm trying to convert query results to data frames. When I run the code (copied from the basic usage examples)
`datatable = ODBC.query(dsn, "show databases")'  
'df = DataFrame(datatable)`

I get the error:
`LoadError: MethodError: convert has no method matching convert(::Type{DataFrames.DataFrame}, ::DataStreams.Data.Table{Array{NullableArrays.NullableArray{T,1},1}})
This may have arisen from a call to the constructor DataFrames.DataFrame(...),
since type constructors fall back to convert methods.WARNING: Error showing method candidates, aborted while loading In[26], in expression starting on line 1 in call at essentials.jl:56`

Any idea why this might be happening? Thanks!

**Comment by quinnj** [comment]
The one thing you need to make sure of is to call
```julia
using DataFrames
```
**before** calling
```julia
using ODBC
```
Essentially, when you call `using ODBC`, it's checking if the `DataFrames` module has already been brought into scope and if so, it defines the right conversion methods. Let me know if that helps.

**Comment by awang94** [comment]
Yeah, that appears to have fixed it. I was calling ODBC before DataFrames. Thanks!
