### ISSUE TITLE
Error on Select queries with empty results. 

### ISSUE THREAD

**Issue by awang94** [JuliaDB/ODBC.jl#126]
When making a SELECT query such as `ODBC.query(dsn, "select * from my_db.persons WHERE my_db.persons.PersonID = 4")` where I know there should be no results returned, I get the error message:
LoadError: UndefRefError: access to undefined reference
while loading In[160], in expression starting on line 1

 in stream! at C:\Users\name\.julia\v0.4\ODBC\src\backend.jl:142
 in query at C:\Users\name\.julia\v0.4\ODBC\src\backend.jl:261

Is this the right behavior? I'm making these select queries to check for duplicate entries in the database, so in most cases the result table should be empty. Thanks!

**Comment by quinnj** [comment]
Definitely shouldn't happen. Can you share what OS and database you're on/connecting to?

**Comment by awang94** [comment]
I'm on Windows 10, connecting to a MySQL database. I can make the same query in MySQL Workbench and get a results grid with null values. The MySQL server is also running on the same computer.

**Comment by quinnj** [comment]
Ok, I think I figured this out. If you do 
```julia
Pkg.checkout("ODBC")
```
that should get you the latest changes and then restart julia to run your code again.
