### ISSUE TITLE
4 issues

### ISSUE THREAD

**Issue by laborhm** [JuliaDB/ODBC.jl#127]
3 issues
- lacking easy conversion from PointerString to AbstractString
- what is the 'valid' conn_string anyway? Any combination of its attributes invokes an ODBC admin window (NOPROMPT does not function as desired?)
- conversion to DataFrames raises errors related to isna(): ERROR: MethodError: `isna` has no method matching isna(::Tuple{PointerString{UInt16},Float64,PointerString{UInt16}}, ::Int64)

UPD in types.jl
replace:
line 6:  @windows_only lib_choices = ["odbc32"]
with:     @windows_only lib_choices = ["odbc", "odbc32"]  #to account for x64/Windows10?

win10 x64

**Comment by ScottPJones** [comment]
I don't think it makes sense to convert to an abstract type.  Conversions should be to concrete types, such as `ASCIIString`, `UTF8String` or `UTF16String`.

**Comment by laborhm** [comment]
How to access the returned values then? 
The following looks intimidating
3-element Array{NullableArrays.NullableArray{T,1},1}:
 NullableArrays.NullableArray{PointerString{UInt16},1}Nullable{PointerString{UInt16}}[]
 NullableArrays.NullableArray{PointerString{UInt16},1}Nullable{PointerString{UInt16}}[]
 NullableArrays.NullableArray{PointerString{UInt16},1}Nullable{PointerString{UInt16}}[]

**Comment by quinnj** [comment]
* to convert from `PointerString` (now `WeakRefString`), just do `string(x)`
* Please clarify what issue or question you have here
* Should be fixed by 99120a1febda35407fe0a963a51e3337aaeb8901

**Comment by laborhm** [comment]
Basically, the questions is how to exclude the ODBC admin window when connecting to a specific db. Looking at the source codes there's no way right now, am i right?
