### ISSUE TITLE
"#undef" after DataFrame conversion

### ISSUE THREAD

**Issue by Neabfi** [JuliaDB/ODBC.jl#128]
Conversion to DataFrame doesn't seem to work.
Before conversion username is like PointerString("myUsername").

`
1x2 Data.Schema:
    id,             username
 Int32, PointerString{UInt8}
Column Data:
	Int32[1]
	PointerString{UInt8}[PointerString("myUsername")]`

After conversion it becomes #undef

`│    Row    │     id     │        username           │ 
├─────┼────┼──────────┤
│      1        │     1      │         "#undef"            │ `

**Comment by quinnj** [comment]
Should be fixed by 99120a1febda35407fe0a963a51e3337aaeb8901
