### ISSUE TITLE
Update information on http://juliadb.github.io/ODBC.jl/

### ISSUE THREAD

**Issue by laborhm** [JuliaDB/ODBC.jl#129]
Update information on http://juliadb.github.io/ODBC.jl/, removing references to nonexisting/misleading  advancedconnect, etc.

**Comment by quinnj** [comment]
Yeah, those docs are pretty old at this point. I'll try to do some docs updates in the next few days.

**Comment by ajkeller34** [comment]
Links to the documentation from the badges seem to be broken.

**Comment by ajkeller34** [comment]
Do you have an idea of when the documentation will be updated? I'd like to use this in my project but I am hesitant to do so without documentation that is kept up to date.

**Comment by quinnj** [comment]
Sorry for the slow response. I'm going to try and get the next update out in the next week or two.

**Comment by quinnj** [comment]
Docs have been updated [here](https://github.com/JuliaDB/ODBC.jl/blob/master/docs/src/index.md) for now. I'm going to get everything re-tagged in the next few days and that will get the docs pushed to the official docs links.
