### ISSUE TITLE
error instead of empty DataFrame

### ISSUE THREAD

**Issue by Neabfi** [JuliaDB/ODBC.jl#130]
If there are no match in the database with our data, it returns an error

> ERROR: UndefRefError: access to undefined reference
 in stream! at /Users/fabien/.julia/v0.4/ODBC/src/backend.jl:142
 in query at /Users/fabien/.julia/v0.4/ODBC/src/backend.jl:261

Why it doesn't return an empty DataFrame ?

**Comment by quinnj** [comment]
Should be fixed by 99120a1febda35407fe0a963a51e3337aaeb8901
