### ISSUE TITLE
Error converting to DataFrame

### ISSUE THREAD

**Issue by msravi** [JuliaDB/ODBC.jl#131]
julia> tables = ODBC.query(mydsn, "show tables")
Data.Table:
2x1 Data.Schema:
     Tables_in_MYDATABASE
 PointerString{UInt16}

        Column Data:
        PointerString{UInt16}[PointerString("MYTABLE1"),PointerString("MYTABLE2")]

julia> d = DataFrame(tables)
ERROR: MethodError: `convert` has no method matching convert(::Type{DataFrames.DataFrame}, ::DataStreams.Data.Table{Array{NullableArrays.NullableArray{T,1},1}})
This may have arisen from a call to the constructor DataFrames.DataFrame(...),
since type constructors fall back to convert methods.WARNING: Error showing method candidates, aborted

 in call at essentials.jl:56

**Comment by quinnj** [comment]
Should be fixed by 99120a1febda35407fe0a963a51e3337aaeb8901
