### ISSUE TITLE
Is this package being maintained? Dependency on DecFP?

### ISSUE THREAD

**Issue by EricForgy** [JuliaDB/ODBC.jl#132]
Hi,

We are interested in getting Julia to access a SQL Server 2016 database. I just added ODBC.jl and am getting a ton of deprecation warnings from DecFP, which seems like it hasn't been updated in over a year.

Should we not use this package? If so, is there an alternative you can recommend?

Thanks

**Comment by EricForgy** [comment]
I just noticed that the deprecation warnings are gone on master. Is there anything holding back tagging a new version?

**Comment by quinnj** [comment]
ODBC.jl is actively maintained and should work fine on 0.4/0.5. Testing has even been done against SQL Server specifically.

DecFP may need a version bump. I'll look into this and bump tonight if needed.

**Comment by EricForgy** [comment]
That is great news! Thank you. After checking out master of DecFP ans some fiddling, we were able to query SQL Server :)
