### ISSUE TITLE
ODBC.listdrivers() does not list all of my drivers

### ISSUE THREAD

**Issue by McNees287** [JuliaDB/ODBC.jl#135]
i'm able to connect to my database with: 
 isql -v DBNAME user password

but when trying to use ODBC.jl, it appears that my driver cannot be found as ODBC.listdrivers() cannot find the driver that was used in isql above.

**Comment by quinnj** [comment]
You'll need to check which ODBC Driver manager is being detected. You can see this by doing `ODBC.API.odbc_dm` and reporting the result. I imagine it's something different than what `isql` is using (i.e. if you have both unixODBC and iODBC installed on the same system)

**Comment by McNees287** [comment]
Appreciate the help. I think i found my problem here. I need to pass a custom connection string through. How can I pass the connection string through? I tried ODBC.DSN("connection string") but this returns this error:
`
[ODBC] IM002: [unixODBC][Driver Manager]Data source name not found, and no default driver specified`

**Comment by quinnj** [comment]
To override, you'll need to edit the ODBC/src/types.jl file and put in a definition like:
```julia
odbc_dm = "path/to/odbc_lib"
```
The reason is because `odbc_dm` is internal to the `ODBC.API` submodule and not exported. I'm going to add a setter function for this so it's even easier in the future to manually set the ODBC lib.

**Comment by McNees287** [comment]
Thank you
