### ISSUE TITLE
How necessary is DecFP?

### ISSUE THREAD

**Issue by simonbyrne** [JuliaDB/ODBC.jl#137]
DecFP is causing some problems on Windows: https://github.com/JuliaLang/julia/issues/18065#issuecomment-240473511

Can we do without it? Or define a new type (e.g. store the decimal as a string, or use a fixed point format)?

**Comment by quinnj** [comment]
DecFP isnt' used on Windows in ODBC, only Linux/OSX. Decimal types are just converted to Floats for now.

**Comment by simonbyrne** [comment]
In that case can we make it a unix-only requirement?

**Comment by quinnj** [comment]
Oh yeah, I forgot we could do that. Yeah, I'll make that change.

**Comment by ScottPJones** [comment]
I'd think for anyone dealing with a database that really is using the decimal types, having *some* working decimal float support is critical, but it doesn't have to be DecFP, if there is an alternative for Windows.
For us at least, Unix-only is just fine ;-)

**Comment by quinnj** [comment]
Ok, this is a unix-only dependency now.
