### ISSUE TITLE
no documentation

### ISSUE THREAD

**Issue by atteson** [JuliaDB/ODBC.jl#140]
The documentation link from github gives a 404.

Given that the interface seems to have changed since the previous versions that I've used, documentation would be helpful.

**Comment by quinnj** [comment]
Just pushed new docs [here](https://github.com/JuliaDB/ODBC.jl/blob/master/docs/src/index.md). There are several other packages that need new tags before I can tag this one, but I'm going to try and get them all re-tagged in the next day or so.

**Comment by ViralBShah** [comment]
Bump. Do the URLs need to be updated for documentation, or will they start working again when the new versions are tagged?

**Comment by quinnj** [comment]
Just waiting on the release. Blocked by a few upstream tags needed first, but I'm hoping soon.

**Comment by ajkeller34** [comment]
Just FYI, the docs badges and text links in README remain broken (though it seems like the docs you've linked to in this issue are up to date). 

Thanks for your work on this package!

**Comment by quinnj** [comment]
The "latest" docs work and are current with the latest tag in terms of functionality: http://juliadb.github.io/ODBC.jl/latest/

**Comment by jpfairbanks** [comment]
I just checked that all 4 documentation links in the readme work. You can probably close this issue.
