### ISSUE TITLE
Column type when using DataFrame as a sink

### ISSUE THREAD

**Issue by tseaward** [JuliaDB/ODBC.jl#144]
When running a query such as `x = ODBC.query(conn, sql)`, any columns in x which are represented as strings in the database (`varchar` etc.) are returned with type `NullableArrays.NullableArray{WeakRefString{UInt8},1}` instead of `NullableArrays.NullableArray{String,1}`.

**Comment by quinnj** [comment]
This is a performance optimization as working with `Vector{String}` can slow things down currently.

**Comment by tseaward** [comment]
Ok. 

If a query returns a large `DataFrame` with several string type columns, and this `DataFrame` goes on to be used by other packages (for analysis/stats/etc.) , would these other packages need to also use `WeakRefStrings` or is there an efficient way to convert all the data to `String`?

**Comment by quinnj** [comment]
Of course it depends on what the downstream packages will be doing with the strings, but basic operations are defined like equality, show, iteration over characters, etc.

To convert, you'd want something like:
```julia
[String(get(x, "")) for x in c]
```
where `c` is a `NullableVector{WeakRefString{T}}`.

**Comment by tseaward** [comment]
I've resorted to the following (adds some overhead for large data sets but seems to work...)

```julia
  s = "select * from table"
  res = ODBC.query(cn, s)

  for n in names(res)
    if typeof(res[n][1]) == Nullable{WeakRefString{UInt8}} ||
      typeof(res[n][1]) == Nullable{WeakRefString{UInt16}}
  
      res[n] = NullableArray([String(get(s, "")) for s in res[n]])
    end
  end
```

**Comment by quinnj** [comment]
I can add a keyword argument or something that avoids `WeakRefString` entirely, it'll make queries slower than if we used `WeakRefString` directly, but should be faster than what' you're doing.

**Comment by tseaward** [comment]
That would be very helpful, thank you.

**Comment by quinnj** [comment]
Alright, got this added on master. It'd be great if you could help test it out. Right now, you can do
```julia
Pkg.checkout("ODBC")
```
to pull current master, then
```julia
ODBC.query(dsn, sql; weakrefstrings=false)
```

**Comment by tseaward** [comment]
This is great. Using a table with 3 out of 10 `varchar` columns and 586493 rows, I get the following times using `weakrefstrings = true`:
```julia
julia> for i = 1:5 @time x = ODBC.query(cn, "select * from table", weakrefstrings = true); end
  7.136286 seconds (36.28 M allocations: 1.172 GB, 5.41% gc time)
  7.067516 seconds (36.28 M allocations: 1.172 GB, 5.35% gc time)
  7.132041 seconds (36.28 M allocations: 1.176 GB, 5.40% gc time)
  7.047281 seconds (36.28 M allocations: 1.176 GB, 5.34% gc time)
  7.169285 seconds (36.28 M allocations: 1.176 GB, 5.40% gc time)
```

And using `weakrefstrings = false`:
```julia
julia> for i = 1:5 @time x = ODBC.query(cn, "select * from table", weakrefstrings = false); end
 10.313436 seconds (36.42 M allocations: 1.014 GB, 35.33% gc time)
 10.820768 seconds (36.42 M allocations: 1.012 GB, 37.55% gc time)
 10.482222 seconds (36.42 M allocations: 1.029 GB, 36.05% gc time)
 10.272293 seconds (36.42 M allocations: 1.013 GB, 34.71% gc time)
 10.389469 seconds (36.42 M allocations: 1.014 GB, 35.78% gc time)
```

And using `weakrefstrings = true` and then converting columns post query (which depends on the number of string type columns): 
```julia
julia> for i = 1:5 @time x = dbquery(cn , "select * from table"); end
  9.871350 seconds (41.56 M allocations: 1.478 GB, 30.22% gc time)
  9.682789 seconds (41.56 M allocations: 1.478 GB, 26.87% gc time)
  9.246300 seconds (41.56 M allocations: 1.478 GB, 24.97% gc time)
  9.778566 seconds (41.56 M allocations: 1.478 GB, 27.19% gc time)
  9.308622 seconds (41.56 M allocations: 1.478 GB, 24.68% gc time)
```
