### ISSUE TITLE
SQL server memory usage / performance

### ISSUE THREAD

**Issue by augustinyiptong** [JuliaDB/ODBC.jl#145]
Hi,

I am seeing high memory usage when reading strings from SQL server:

sql_query = """select top 1 cast(name as char(1)) from mytable"""
dsn = ODBC.DSN(connection_string, prompt=false)
@time df1 = ODBC.query(dsn, sql_query)
@time df2 = ODBC.query(dsn, sql_query)
@time df3 = ODBC.query(dsn, sql_query)
@time df4 = ODBC.query(dsn, sql_query)
@time df5 = ODBC.query(dsn, sql_query)
@time df6 = ODBC.query(dsn, sql_query)
ODBC.disconnect!(dsn)
  0.001646 seconds (249 allocations: 657.516 KB)
  0.002606 seconds (257 allocations: 18.219 KB)
  0.001265 seconds (249 allocations: 657.516 KB)
  0.002547 seconds (257 allocations: 18.219 KB)
  0.001312 seconds (249 allocations: 657.516 KB)
  0.002832 seconds (257 allocations: 18.219 KB)

If i now change the query to return 2 chars instead of 1 and run the same code:
sql_query = """select top 1 cast(name as char(2)) from mytable"""
  0.001709 seconds (249 allocations: 721.516 KB)
  0.002964 seconds (257 allocations: 18.219 KB)
  0.001308 seconds (249 allocations: 721.516 KB)
  0.002769 seconds (257 allocations: 18.219 KB)
  0.001378 seconds (249 allocations: 721.516 KB)
  0.002496 seconds (257 allocations: 18.219 KB)

It looks like it uses 64 KB of memory for a single extra character. And in my code i run into performance issues with larger queries.

Also it seems like every other run has much lower memory usage. I am obviously running the query only once in my real code.

I am using ODBC 0.5.1 on julia 0.5.0 on windows.

I previously used ODBC 0.3.x with much lower memory usage (of the order of bytes per extra char) / better performance

Thanks, Gus

**Comment by augustinyiptong** [comment]
Hi,

I made this change: #149 and it runs (apparently) without ill effects. Thanks, Gus

**Comment by quinnj** [comment]
Closed via #149
