### ISSUE TITLE
varchar(max) in Sql Server 2012 returns empty Nullable{WeakRefString{UInt8}}

### ISSUE THREAD

**Issue by mmsteven** [JuliaDB/ODBC.jl#146]
Query for columns with varchar(max) type returns an empty string. See example below. Happy to provide more detail if needed.

julia example 

```julia
julia> VERSION
v"0.5.0"

julia> Pkg.status("ODBC")
 - ODBC                          0.5.1

# ... create dsn 

julia> sql = "SELECT PositionDescription FROM MyTable WHERE ID=1"
"SELECT PositionDescription FROM MyTable WHERE ID=1"

julia> result = ODBC.query(dsn, sql)
1×1 DataFrames.DataFrame
│ Row │ PositionDescription │
├─────┼─────────────────────┤
│ 1   │ ""                  │

julia> typeof(result[1,:PositionDescription])
Nullable{WeakRefString{UInt8}}

julia> isnull(result[1,:PositionDescription])
false

julia> x = result[1,:PositionDescription].value
""
```

The same request (using the same DSN) in python returns correctly (so it is not a problem with the database):

```python
>>> cursor = conn.cursor()
>>> result = cursor.execute("SELECT PositionDescription FROM MyTable WHERE ID=1").fetchall()
>>> result
[('BAKER HUGHES INC', )]
```

The column information is:
```python
>>> sql = "select COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, CHARACTER_OCTET_LENGTH, CHARACTER_SET_NAME FROM information_schema.columns where table_name = 'MyTable' and COLUMN_NAME='PositionDescription';"
>>> cursor.execute(sql).fetchall()
[('PositionDescription', 'varchar', -1, -1, 'iso_1')]
```

**Comment by augustinyiptong** [comment]
I am also using sql server 2012. varchar(MAX) works for me. My query returns:
`Nullable{String}("test TEST")`

Could it be you are on a different version of DataFrames? I have:
`DataFrames                    0.8.5`

**Comment by mmsteven** [comment]
Thanks for the suggestion.  I double checked and the DataFrames version is 0.8.5.

As an aside:
I did notice that you had a `Nullable{String}` instead of the `Nullable{WeakRefString{UInt8}}` so I tried the query with `weakrefstrings=false` and got an empty `Nullable{String}`, so that doesn't solve the problem either.

**Comment by quinnj** [comment]
@mmsteven, sorry for the long delay here. Can you tell me what database you're seeing this problem with? That way I may have a chance at reproducing.

**Comment by mmsteven** [comment]
Hey @quinnj 

The database itself is an internal database that doesn't have public access.  

It seems that others are not having this problem though so it is probably not something simple, and could very well be on my end.

That said, this is not a high priority issue for me right now.  I just changed the tables to not use varchar max and everything is working just fine.  We are in the middle of a number of upgrades/migrations, one of which is to Julia v0.6.  Once the dust settles I will set up some tests to re-evaluate this and see if I can get you any further details (assuming it persists).

**Comment by quinnj** [comment]
Sounds great. I currently am working on the `jq/0.6` branch, which loads and passes tests on 0.6. I'm trying to go through issues and polish things up before merging.

**Comment by quinnj** [comment]
Feel free to re-open if this is still an issue.
