### ISSUE TITLE
Newbie to Julia, not able to use ODBC.jl

### ISSUE THREAD

**Issue by arafangion** [JuliaDB/ODBC.jl#147]
I am struggling with the documentation for this, and want to connect to an MS SQL Server we have running.  Whilst I have been able to use pymssql, via the python bindings, I would prefer to do this in "native" julia code without interacting with an FFI.

I have tried the following code:
> using ODBC
> println(ODBC.listdrivers)
> println(ODBC.listdsns())

I expected that they would show me the list of drivers I have installed, along with a list of dsn's, however, I only get:

> ODBC.listdrivers

As the output.  As per docs, I was expecting a list of configured drivers.

Assuming that this list is empty, how do I get the mssql bindings installed?

I am using Julia 0.4 within Jupyter, on mac os x.

Thanks.

**Comment by mmsteven** [comment]
This might just be a typo in your question, but listdrivers is a function:

```
julia> ODBC.listdrivers
listdrivers (generic function with 1 method)

julia> println(ODBC.listdrivers)
ODBC.listdrivers

julia> println(ODBC.listdrivers())
String["ODBC Driver 11 for SQL Server" "Description=Microsoft ODBC Driver 11 for SQL Server\0Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-11.0.so.2270.0\0Threading=1\0UsageCount=1\0"; "ODBCSQL" "Description=Microsoft ODBC Driver 11 for SQL Server\0Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-11.0.so.2270.0\0Threading=1\0UsageCount=1\0"]

```

**Comment by arafangion** [comment]
Thanks mmsteven, however I don't get that result. The reason I had tried the 'ODBC.listdrivers' form, was because that's what the documentation says at http://juliadb.github.io/ODBC.jl/latest/

It seems that using the julia interpreter results in slightly better diagnostics, so I've shown what my interpreter shows me below, it seems that I somehow don't have any drivers installed:

```julia> using ODBC

julia> println(ODBC.listdrivers())


julia> 
```

How do I install a driver?

**Comment by augustinyiptong** [comment]
Hi, perhaps you need this:

https://www.microsoft.com/en-us/download/details.aspx?id=36434

**Comment by arafangion** [comment]
Hello @augustinyiptong, I believe that download only works on Microsoft operating systems.

**Comment by arafangion** [comment]
I should add that I have now installed Julia 0.5, and the same problems remain.

**Comment by mmsteven** [comment]
@arafangion I was able to get the odbc drivers installed on my MAC by following the steps here:

https://github.com/lionheart/django-pyodbc/wiki/Mac-setup-to-connect-to-a-MS-SQL-Server

Everything worked fine with the installation (I'm on Sierra) and isql and pyodbc picked up the changes no problem.  Note, if you are on sierra, make sure you have an up to date version of brew (1.0 or greater I think)

However... to get julia ODBC working I had to do the following:

* remove iODBC  (I'm not sure this was 100% necessary though)
* reboot the Mac -- for some reason the steps below didn't work the first time... could have just been user error... but after the reboot it worked... so... worth a try I guess.
* reinstall the odbc module
```julia
julia> Pkg.rm("ODBC")
# get the shell by hitting ';'
shell> rm -rf $(Pkg.dir())/.cache/ODBC
julia> Pkg.add("ODBC")
```


HTH

**Comment by arafangion** [comment]
@mmsteven,
Thanks for that excellent link, I had no trouble with those steps, though I will note that pyodbc already works flawlessly.  Consequently I did skip the various .ini files and .conf file configuration.

However, I see no changes to ODBC.listdrivers() - it still reports no drivers whatsoever.

Changing the topic, lets assume that ODBC is somewhat tricky to configure: How do I just get this working with just sqlite3?  I don't have an sqlite3 driver either, for some reason.

**Comment by McNees287** [comment]
Might I suggest calling pyodbc via PyCall? That's what I currently use and it works very well.

I've never been able to get ODBC.jl to work.  Hopefully, with time it will be become more robust.

**Comment by arafangion** [comment]
Hello @McNees287, that is what I am currently doing for the moment. :)

However, I would like a native solution to be developed, and currently ODBC.ij seems to be the best option for this. Eventually, with time, the documentation will mature and hopefully this question will be answered. :)

**Comment by quinnj** [comment]
Yes,  ODBC can be a bit tricky to get installed on OSX. It really depends on if you want to stick w/ IODBC, which was apple's stab at ODBC which it seems they've since abandoned, or the unixODBC route, which I've personally had more success with. The link that @mmsteven shared above is indeed the right way to go about getting unixODBC installed.

**Comment by jpfairbanks** [comment]
The link above seems to require stuff for MSSQL specifically. Is it intended that `brew install unixodbc && julia -e 'Pkg.add("ODBC")'` be enough to install `ODBC.jl` on OSX?

**Comment by quinnj** [comment]
@jpfairbanks, that should be enough for installation on OSX.

Anyone, feel free to ask any other questions here if needed: I'm just closing since I don't think there's anything actionable here.
