### ISSUE TITLE
implement `prepare`, `execute` functions

### ISSUE THREAD

**Issue by kmsquire** [JuliaDB/ODBC.jl#15]
Currently, `query` immediately sends information to the database and returns the response.  It would be nice to have `prepare` and `execute` statements as well, for queries which will be used repeatedly.

ODBC supports this, of course, and `ODBC.jl` already implements the low level calls

Unless you already have some code for this, I'll work on implementing it, as I have use for this now.

**Comment by quinnj** [comment]
Alright, this is now implemented in the form of `ODBC.prepare(dsn, sql) => ODBC.Statement`, and `ODBC.execute!(stmt[, values])`. More in the docs [here](https://github.com/JuliaDB/ODBC.jl/blob/master/docs/src/index.md)

**Comment by quinnj** [comment]
(p.s. sorry for taking 3 years on this!!)
