### ISSUE TITLE
Please add back support for julia 0.4

### ISSUE THREAD

**Issue by bluesmoon** [JuliaDB/ODBC.jl#151]
We use ODBC in an application we build for several customer who have very long upgrade cycles (some do not upgrade more than twice a year), we've only recently managed to move everyone from julia 0.3 to julia 0.4 so it will be a very long time before we can move them to 0.5.

Could you add back support for julia 0.4 so that we can continue to use the latest version of ODBC?

**Comment by quinnj** [comment]
This would require more work that I'm personally able to put in, but I'm happy to review a PR that re-enabled 0.4 functionality. Do note, however, that Julia 0.6 is set to be released in the next month or so and Julia 1.0 it set to be released this summer; the idea is to encourage rapid development of remaining "1.0" issues/features to enable a long period of stability/maintenance with 1.0.

**Comment by bluesmoon** [comment]
Unfortunately commercial customers do not upgrade that quickly.  Our customers would take at least another 2-3 years to get onto 1.0.

IAC, we no longer need this as we've switched to a python backed DBI interface for database access, so I'm closing this request.
