### ISSUE TITLE
Unsupported Array{DataType} 

### ISSUE THREAD

**Issue by alblaz** [JuliaDB/ODBC.jl#156]
I modified the example given in the ODBC.jl documentation in order to insert arrays of floats in a table of a Postgresql database.

```
dsn = ODBC.DSN(valid_postgresql_dsn)
stmt = ODBC.prepare(dsn, "INSERT INTO cool_table VALUES(?, ?, ?)")
ODBC.execute!(dsn, "CREATE TABLE cool_table (col1 INT, col2 FLOAT ARRAY, col3 VARCHAR(255))")
df = DataFrame(col1=[1,2,3], 
               col2=[[1.0, 2.0, 3.0],[4.,5.,6.],[7.,8.,9.]] , 
               col3=["hey", "there", "sailor"])
for row = 1:size(df, 1)
    ODBC.execute!(stmt, [df[row, x] for x = 1:size(df, 2)])
end
```

This code results in
```
"ERROR: KeyError: key Array{Float64,1} not found
 in getindex at .\dict.jl:688 [inlined]
 in execute!(::ODBC.Statement, ::Array{Any,1}) at C:\Users\alaz\.julia\v0.5\ODBC\src\Source.jl:73
 in macro expansion; at .\REPL[47]:2 [inlined]
 in anonymous at .\<missing>:?"
```

Arrays are supported by Postgresql but it seems that currently this datatype is not supported by ODBC.jl.
Is that correct? Are there plans to support Arrays?

Thanks!

**Comment by quinnj** [comment]
You are correct that this is currently not supported, mainly because most databases don't support this. The road to support is probably not too bad though; we'd need to figure out what type code postgres returns for an Array column and then do the appropriate `cast` methods.

**Comment by quinnj** [comment]
Hmmmm, in my preliminary research, it doesn't look like postgres supports working w/ Arrays natively through ODBC (e.g. when trying to retrieve an array from a postgres db, it just returns it as a string). Given that knowledge, I was able to successfully insert an Array via a direct SQL query like
```julia
ODBC.execute!(dsn, "insert into test1 VALUES
                    (1, -- bigint,
                     ARRAY[1, 2, 3] -- integer array
                    )")
```
