### ISSUE TITLE
Changes to WeakRefString permanently break query functionality

### ISSUE THREAD

**Issue by pazzo83** [JuliaDB/ODBC.jl#171]
Hi, it looks like some changes to the WeakRefString constructor (https://github.com/quinnj/WeakRefStrings.jl/commit/7de909beab3e586b2a68497623bcded88c1d5ead) have since broken at least the "cast!" method that gets called when you run a query.  Currently, on line 290 of that method (in Source.jl), the constructor is as such:
```julia
values[i] = length == 0 ? WeakRefString{T}(Ptr{T}(0), 0, 0) : WeakRefString{T}(pointer(parent, ind), length, ind)
```
However, now the WeakRefString constructor only takes two arguments because the struct itself only has two attributes:
```julia
struct WeakRefString{T} <: AbstractString
    ptr::Ptr{T}
    len::Int # of code units
end

WeakRefString(ptr::Ptr{T}, len) where {T} = WeakRefString(ptr, Int(len))
WeakRefString(t::Tuple{Ptr{T}, Int}) where {T} = WeakRefString(t[1], t[2])
```

Thanks!

Chris Alexander

**Comment by pazzo83** [comment]
There is a reference to this issue over on the WeakRefString side: https://github.com/quinnj/WeakRefStrings.jl/issues/10

**Comment by quinnj** [comment]
Fixed on master
