### ISSUE TITLE
query() documentation wrong about copying results to file ODBC 0.3.8 (both Julia 0.2 and 0.3-prerelease)

### ISSUE THREAD

**Issue by dierickx3** [JuliaDB/ODBC.jl#50]
It took me a while to figure out (more like guess) that if you want to copy the query results to an external file then it's really <b>query(querystring::ASCIIString, connection::Connection=conn, output::ASCIIString="PathToOutputFile.txt", delim::Char='\t')</b> and not what the documentation here on the main page shows. 

That is, the parameter called "file" needs to be called "output" . Also, if supplying an explicit connection parameter, looks like it needs to go <i>after</i> the querystring, not <i>before</i>

For example <i>(on Windows, to copy results to pipe delimited file)</i>: 
<pre>query("select * from dbo.MyTable", <b>output</b>="C:\\Temp\\test.txt", delim='|')</pre>

or

<pre>query("select * from dbo.MyTable", conn, <b>output</b>="C:\\Temp\\test.txt", delim='|')</pre>

p.s. even if you don't care about writing a copy of the results to file, the optional connection parameter looks like it's supposed to go second rather than first, like so::

<pre>query("select * from dbo.MyTable")</pre>

or

<pre>query("select * from dbo.MyTable", conn)</pre>

**Comment by quinnj** [comment]
fixed by 7ae7ebfac60ed3ffb1ccefd552993a3073f8b77b
