### ISSUE TITLE
Bug in ODBCDirectToFile() function (using ODBC 0.3.8 with Julia 0.3.0-prelease)

### ISSUE THREAD

**Issue by dierickx3** [JuliaDB/ODBC.jl#51]
If trying to export to file like so:

<code>query(qry, conn, output="C:\\\\Temp\\\\test.txt", delim='|')</code> 

you will get an error message:

<b style="color: red">ERROR: no method ODBCClean(Array{Uint8,2}, Int64)
 in ODBCDirectToFile at C:\Julia64\.julia\v0.3\ODBC\src\backend.jl:234 </b>

What appears to be happening behind the scenes when the above query() function <i>(defined in "userfacing.jl")</i> is called with the optional parameter "output" and a file path, is the query() function then employs the ODBCDirectToFile() function in "backend.jl" and inside this function there's a call to ODBCClean() function, with varying signatures, but none that match the signature of what is being called here.

So, what seems to fix it is supplying the length of the first parameter as the third parameter (currently missing in 0.3.8); 

currently:
<code>write(out_file,ODBCEscape(ODBCClean(columns[col],row)))</code>

should be (?):
<code>write(out_file,ODBCEscape(ODBCClean(columns[col],row,<b>length(columns[col])</b>)))</code>

ALSO, when writing out from a SQL VARCHAR(n) field to file, it appends a bunch of trailing NUL ASCII character codes (\0) such that the entire string written out is n characters long. In other words, it doesn't "rtrim" the trailing empty characters. It looks like by wading through "ODBC_Types/jl" that SQL VARCHAR(n) fields are interally stored an array of uint8 character codes. So, to get rid of the trailing null character codes (really, to get rid of them all, which seems safe to do), if you were to change the following line in "backend.jl" then it exports as expected:

currently:
<code>ODBCClean(x::Array{Uint8},y,z) = bytestring(x[1:z,y])</code>

should be(?):
<code>ODBCClean(x::Array{Uint8},y,z) = <b>replace(</b>bytestring(x[1:z,y])<b>,r"\0","")</b></code>

**Comment by quinnj** [comment]
should be fixed by 7ae7ebfac60ed3ffb1ccefd552993a3073f8b77b
