### ISSUE TITLE
querymeta() function broken in ODBC.jl 0.3.8 with Julia 0.3.0-prerelease?

### ISSUE THREAD

**Issue by dierickx3** [JuliaDB/ODBC.jl#54]
I get the following with any query I try with Julia 0.3.0-prerelease, but had no problems with Julia 0.02 as of last week:

<pre>
julia> querymeta(qry)
Resultset metadata for executed query
------------------------------------
Query: SELECT MyVarChar, MyInt FROM dbo.ExampleDataColumns: 2
Rows: -1
<b>WARNING: DataFrame(::Matrix, ::Vector)) is deprecated, use convert(DataFrame, Matrix) instead
 in depwarn at deprecated.jl:36
 in DataFrame at C:\Julia64\.julia\v0.3\DataFrames\src\deprecated.jl:54
 in show at C:\Julia64\.julia\v0.3\ODBC\src\ODBC.jl:37</b>
Error showing value of type Metadata:
<b>ERROR: no method Index(Array{ASCIIString,1})
 in DataFrame at C:\Julia64\.julia\v0.3\DataFrames\src\deprecated.jl:61
 in show at C:\Julia64\.julia\v0.3\ODBC\src\ODBC.jl:37</b>
</pre>

**Comment by quinnj** [comment]
method no longer exists after 7ae7ebfac60ed3ffb1ccefd552993a3073f8b77b
