### ISSUE TITLE
SQL Server Data Type Test Results

### ISSUE THREAD

**Issue by dierickx3** [JuliaDB/ODBC.jl#55]
Very small table with small samples and here's what I see:

VARCHAR(n) .... works with workaround I mentioned in issue #51 
VARCHAR(MAX) ... throws an out of bounds error
NTEXT .............. blows up my machine per Issue #53 
Integer  ............ good
BigInt ............... good
SmallInt ........... good
TinyInt ............. works with workaround I mentioned in Issue #52 
Float ............... good
Decimal .......... good
Date ............... good
Time ,,,,,,,,,,,,,,, good
DateTime ........ good (makes it UTC rather than local, but can live with that)

**Comment by quinnj** [comment]
should be fixed by 7ae7ebfac60ed3ffb1ccefd552993a3073f8b77b; there's still an outstanding issue for NTEXT or LONGTEXT fields
