### ISSUE TITLE
NULL values create "weird" situation when exporting query to file

### ISSUE THREAD

**Issue by dierickx3** [JuliaDB/ODBC.jl#56]
It looks like NULL values in database come over into DataFrame as NA fine, but if you try exporting to text file (i.e. query(qty, output="test.txt", delim='|') then wherever there were NULL values, they're replaced in the text file with whatever was last populated from a previous record.

For example,
<pre>
123
456
NULL
NULL
ABC
</pre>

gets exported like this:
<pre>
123
456
<b>456</b>
<b>456</b>
ABC
</pre>

**Comment by quinnj** [comment]
should be fixed by 7ae7ebfac60ed3ffb1ccefd552993a3073f8b77b
