### ISSUE TITLE
How do I get connection string back?

### ISSUE THREAD

**Issue by randyzwitch** [JuliaDB/ODBC.jl#59]
If you call `advancedconnect()` on Windows with no arguments, it pops up the ODBC manager and lets you pick a DSN. I am able to connect to my database just fine, but I'd like to be able to script my connection later on.

Is there a way to get the full connection string back? I've tried `conn` and `Connections` objects at the REPL, but all I get back are PTR references. 

(@quinnj, I figured out my DSN issue which was leading me to ask this question in the first place, so this isn't a critical issue, just a nice-to-have in the future)

**Comment by quinnj** [comment]
you now get the connection string back when connecting via `ODBC.DSN(connection_string)`
