### ISSUE TITLE
Writing query to file appends one too many tabs

### ISSUE THREAD

**Issue by randyzwitch** [JuliaDB/ODBC.jl#60]
If I run `query()` with a tab delimiter, the file writes fine to disk. However, a tab is placed after the right-most column, then the CRLF line breaks are written. For a 4 column file, this implies 5 columns.

When I tried to load this to a database, it complains about "extra information" being contained in the file. Removing the trailing tab from the first couple of records allows me to load it in the database.

**Comment by quinnj** [comment]
should be resolved by 7ae7ebfac60ed3ffb1ccefd552993a3073f8b77b
