### ISSUE TITLE
ODBC query errors

### ISSUE THREAD

**Issue by Maple-Wang** [JuliaDB/ODBC.jl#61]
I do not kown how to do.  Thanks for your help.

julia> using ODBC

julia> conn = ODBC.connect("DSN1",usr="wangfeng",pwd="wangfeng")
ODBC Connection Object
Connection Data Source: DSN1
DSN1 Connection Number: 7
Connection pointer: Ptr{Void} @0x000000000bb47b10
Statement pointer: Ptr{Void} @0x000000000bb47e90
Contains resultset? No

julia> query(connection::Connection=conn,"SHOW TABLES;"; file=:DataFrame,delim='
\t')
ERROR: syntax: keyword argument is not a symbol: (:: connection Connection)

**Comment by aviks** [comment]
@Maple-Wang does the above comment fix your issues? Can this issue be closed?
