### ISSUE TITLE
Error while using LIMIT with OFFSET

### ISSUE THREAD

**Issue by KAppleton** [JuliaDB/ODBC.jl#77]
I am trying to get a range of rows and have tried the following syntax styles with no luck :

"select * from mytable order by first_column limit 10,10"
"select * from mytable order by first_column limit 10 offset 10"

I appear to get the following error in both cases :      
"ERROR : invalid UTF-8 squence
         in convert at utf8.jl:162 (repeats 2 times)"

Does the ODBC package support the ability to retrieve a range of rows?  Any help would be greatly appreciated.

Thanks.

**Comment by quinnj** [comment]
dup of #67
