### ISSUE TITLE
SQLTimestamp Issue with file streaming and dataframes

### ISSUE THREAD

**Issue by KAppleton** [JuliaDB/ODBC.jl#78]
I am using Julia v0.3

I am using a query of the following type : 
     query("select * from mytable", output = "C:\\MyFile.csv",delim = ',')

and I get the following error : 
     ERROR: 'ODBCClean' has no method matching ODBCClean(::Array(SQLTimestamp,1), ::Int64)

Is there a way to easily fix this so I can stream to CSV?

If I pull this back as a DataFrame using syntax similar to : 
     TestDataFrame = query("select * from mytable limit 10)

I see that the date columns have the data described as following : 
SQLTimeStamp(2015,01,01,0,0,0,0)

There appears to be a base.string overloaded method for this but it isn't used on the import, is there an easy way to convert all this information back into the original 2014-01-01 styled date on import?

Many thanks,

**Comment by quinnj** [comment]
should be fixed by the overhaul 7ae7ebfac60ed3ffb1ccefd552993a3073f8b77b
