### ISSUE TITLE
Unicode errors on Windows on Julia 0.3.7

### ISSUE THREAD

**Issue by aaalexandrov** [JuliaDB/ODBC.jl#81]
When executing queries I was getting various syntax errors on correct queries and occasionally a utf8 conversion error. I was getting different errors each time with the same query. After investigating a little I found this utf16 conversion
```julia
function ODBCQueryExecute(stmt::Ptr{Void}, querystring::String)
    if @FAILED SQLExecDirect(stmt, utf16(querystring))
        ODBCError(SQL_HANDLE_STMT,stmt)
        error("[ODBC]: SQLExecDirect failed; Return Code: $ret")
    end
end
```
Inside SQLExecDirect however the ccall casts this to Ptr{Uint8}, so I guess that triggers an implicit conversion from utf16 to utf8 and that was the source of the utf conversion errors.
Removing the utf16 conversion upon calling SQLExecDirect fixed all the errors and from that point on the package worked as expected.
I'm not entirely sure if this is the right way to fix the issue, however a serious issue does exist.
Also, the published version still has the 'evn' error in advancedconnect(), I had to fix that too to get it to work.

**Comment by aviks** [comment]
Probably the same as #67

**Comment by quinnj** [comment]
dup of #67
