### ISSUE TITLE
Setting of odbc_dm needed on 64-bit Windows with 64-bit Oracle

### ISSUE THREAD

**Issue by AndyGreenwell** [JuliaDB/ODBC.jl#86]
As requested in the [Known Issues](https://github.com/quinnj/ODBC.jl#known-issues) section of the README, this issue is being opened due to a need to use `const odbc_dm = "C:\\Windows\\System32\\odbc32.dll"` when connecting to a 64-bit Oracle database running on a 64-bit Windows 10 preview OS image.  

As shown in the attached screenshot: ![odbcwithoracle](https://cloud.githubusercontent.com/assets/11096243/8058631/bff79206-0e88-11e5-8c7f-280139532a48.PNG) connecting successfully required two steps to be performed.  The setting of `const odbc_dm` needed to be performed before executing `using ODBC`, and a System DSN entry for the database of interest needed to be added as a 64-bit ODBC data source.  The second step is independent of Julia but might be helpful to add to the documentation of this package for use on Windows.

The second attached screenshot shows the error message received when performing a query against the same database if the `const odbc_dm = "C:\\Windows\\System32\\odbc32.dll"` is not performed prior to `using ODBC`.  The same System DSN entry is present on this system with this second screenshot.

![odbcwithoracleno_odbc_dm](https://cloud.githubusercontent.com/assets/11096243/8058632/bffbeda6-0e88-11e5-8c14-786182ee5421.PNG)

**Comment by quinnj** [comment]
Hmmmm.....this seems odd. It should be picking up `odbc32.dll` automatically. I'm working on an overhaul, so I'd appreciate it you could test changes as they get pushed.

**Comment by AndyGreenwell** [comment]
Any chance it is currently picking up C:\Windows\SysWOW64\odbc32.dll by default (instead of C:\Windows\System32\odbc32.dll) when on a 64-bit machine?

And, yes, I will test any changes that you make.

**Comment by quinnj** [comment]
hey @AndyGreenwell, I know this is like a year late, but if you'd be willing ot try latest master, I've finally merged the overhaul. Let me know if you're still seeing issues here.

**Comment by AndyGreenwell** [comment]
I'll need to recreate that test environment, but yes I will perform this test as soon as feasible.

**Comment by quinnj** [comment]
Great. And let me know if you see any other issues. I have test environments set up on my end currently for MySQL, Teradata, and SQL Server, with PostgreSQL and Oracle coming soon.

**Comment by AndyGreenwell** [comment]
Using the current ODBC.jl master with the [new usage instructions](https://github.com/JuliaDB/ODBC.jl/blob/master/README.md), I can confirm that one can execute successfully the example query in the above screenshots without needing to set `const odbc_dm` prior to the execution of `using ODBC` when connecting to a 64-bit Oracle installation's DSN running on 64-bit Windows with 64-bit Julia.

**Comment by quinnj** [comment]
Great news. Thanks for checking this out @AndyGreenwell. Do let me know if you run into any other issues on the new ODBC release or if there are any big features that would be helpful for you.
