### ISSUE TITLE
BoundsError in backend.jl

### ISSUE THREAD

**Issue by LouisMagarshack** [JuliaDB/ODBC.jl#87]
Connecting to Redshift using the Mac OS X ODBC driver, I get a `BoundsError` in `backend.jl` at line 147 (in function `@compat function ODBCCopy!(dest::Array{UTF16String},dsto,src::Array{UInt16,2},n,ind,nas)`).
It seems that `div(ind[i], 2)` is greater than `size(src, 1)` (in my case 2550 vs 2048).

I looked at the contents of src (using Debug.jl) and it is of the form `\h\0\t\0\t\0\p\0\:\0...` so that using
`raw = src[1:2:min(end, div(ind[i], 2)) , i]` solves my issue. But it shouldn't...

(On a separate note, with the same ODBC driver, I'm getting the following error somewhat frequently: `[ODBC] 07002: [Amazon][ODBC] (10690) At least one expected descriptor record does not exist during query execution.`
Should I create a separate issue for this?

**Comment by quinnj** [comment]
should be resolved by the major overhaul (7ae7ebfac60ed3ffb1ccefd552993a3073f8b77b); please re-open if you're still seeing issues.
