### ISSUE TITLE
move to JuliaDB org?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaDB/ODBC.jl#88]
Seems like there's a collection of database stuff here: https://github.com/JuliaDB.

cc: @quinnj, @johnmyleswhite, @iamed2

**Comment by StefanKarpinski** [comment]
Related: https://github.com/iamed2/PostgreSQL.jl/issues/13

**Comment by ScottPJones** [comment]
Unfortunately, that seems rather moribund... it looks like any database activity in the last 11 months has been taking place in JuliaLang instead (and even those have not had much happening... I know that @quinnj has been busy, so not much as been going on for a while with `ODBC.jl`, hopefully that will change soon?)

**Comment by quinnj** [comment]
I'm about half-way through an overhaul for ODBC.jl. Hey @ScottPJones, mind looking into https://github.com/stevengj/DecFP.jl/issues/14 for me? I know you'd be interested in that integration.

**Comment by ScottPJones** [comment]
Yes, I saw that, I was waiting for @stevengj to comment on it first...  I guess he must be pretty busy...
I'll be looking forward to anything you do on `ODBC.jl` (I *still* have hopes to move back to Julia for our RDBMS connections by next year... I'm not such a big fan of Python...)

**Comment by josefsachsconning** [comment]
@quinnj, could you possibly describe somewhere (maybe a new or existing issue, but I couldn't find one) what you have in mind for the overhaul that you mentioned yesterday?  We would be very interested in beta testing.

**Comment by StefanKarpinski** [comment]
Would also be happy to help with alpha/beta testing.

**Comment by quinnj** [comment]
done.
