### ISSUE TITLE
Could master please be published to METADATA.jl?

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaDB/ODBC.jl#89]
METADATA.jl is currently using 0.3.10 from Oct 2.
There's a bug fix from Dec 11 (03305ea) merged into master Apr 9 (118790e) that would be nice to have.

At the same time, maybe the GitHub repo could be tagged with the new tag in METADATA?  The repo currently only has 0.3.6 and 0.3.7 tags/releases.

**Comment by quinnj** [comment]
dup of #94
