### ISSUE TITLE
Drivers for vertica

### ISSUE THREAD

**Issue by Userstep1** [JuliaDB/ODBC.jl#90]
I'm using ODBC.jl for querying both MySQL and Vertica, MySQL queries work well but Vertica queries does not work at all.
My odbc.ini is well configured since I use the same DSN in R (using RODBC) and it works. 

The connection object does not make any problems:
```
julia> con = ODBC.connect("vertica1") 
ODBC Connection Object
Connection Data Source: vertica1
vertica1 Connection Number: 1
Contains resultset(s)? No
```
But using `query` caused problems:
```
julia> query("SELECT * FROM names;", con)
[ODBC] 42601: ERROR 4856:  Syntax error at or near "\" at character 21

ERROR: [ODBC]: SQLExecDirect failed; Return Code: SQL_DEFAULT_ERROR
 in error at error.jl:21
 in ODBCQueryExecute at /home/ubuntu/.julia/v0.3/ODBC/src/backend.jl:44
 in query at /home/ubuntu/.julia/v0.3/ODBC/src/userfacing.jl:46
```

Just to make it clear - there are no syntax errors and the same query runs perfectly using RODBC or directly in Vertica.

I tried changing `odbc_dm` (before or after calling 'using ODBC')
` const odbc_dm="/opt/vertica/lib64/libverticaodbc.so" `
but it still did not work.

Any suggestion on how to use ODBC.jl and Vertica?
Is there a way to add Vertica's drivers to the drivers list?
Thanks!

**Comment by niczky12** [comment]
Hi!

I'm having the same issues on Windows.

Run a query and got the same error. Whereas the query runs fine on DBeaver so syntactically it's correct.

A solution would be most welcome.

**Comment by quinnj** [comment]
For any who have had problems connecting to Vertica, I'm sorry for the lack of response and follow up here. I'm actively working on the package again and am just about finished with an overhaul of the package. I'd appreciate being able to test the new framework if anyone is willing to help. Just let me know and I can talk you through setup and we can work on troubleshooting/fixing anything that comes up.

**Comment by niczky12** [comment]
Hi @quinnj,

I managed to fix this by changing the encoding. See my comment on issue #71.

It's running fine on windows with that simple change. I'm assuming the encoding should take into consideration the platform it's running on.

Thanks for looking into this.

**Comment by quinnj** [comment]
Ah, that's good to hear. Would you mind doing a quick test or two for me on the new package overhaul? You can get the code by doing the following with any Julia 0.4 release

```julia
Pkg.add("ODBC")
Pkg.checkout("ODBC","jq/remodel")
Pkg.checkout("DataStreams")
Pkg.checkout("CSV")
Pkg.checkout("SQLite")
```
then usage is like:
```julia
using DataStreams, ODBC
conn = ODBC.DSN("[vertica_dsn]")
source = ODBC.Source(conn, "select * from [some_table]")
dt = Data.stream!(source, Data.Table)
```

**Comment by niczky12** [comment]
Hi @quinnj!

Sorry about the delay in getting back to you.

I can confirm that the above works okay on windows 7 with vertica.

Let me know if you need me to do any more testing. I'd be happy to support this project in whatever way I can.

Thanks

**Comment by niczky12** [comment]
@quinnj 

On the other hand I'm not able to convert the Data.Table to dataframe. Which is a bit annoying so I'm reverting to the old version.

**Comment by quinnj** [comment]
Hey @niczky12, just a follow up here: with a `Data.Table`, its package comes with a definition to convert (non-copying) to a DataFrame. Just call `DataFrame(dt::Data.Table)`. Let me know if you have any other issues.
