### ISSUE TITLE
Building out a robust test environment

### ISSUE THREAD

**Issue by quinnj** [JuliaDB/ODBC.jl#91]
@AndyGreenwell, this is what I see as a good starting basis

|  | Windows | OSX | Linux |
| --- | --- | --- | --- |
| MySQL | @quinnj | @quinnj |  |
| SQL Server |  |  |  |
| PostgreSQL |  |  |  |
| Oracle |  |  |  |
| Teradata | @quinnj |  |  |
| SQLite | @quinnj | @quinnj |  |

If others would like a particular system tested, please comment/edit here and state what DB + Platform you could test on. Eventually, we'd put this table on the repo README to advertise what is known to work well.

**Comment by StefanKarpinski** [comment]
Does SQLite make sense? (Are there even ODBC drivers for that?)

**Comment by quinnj** [comment]
[Looks like there is](http://www.ch-werner.de/sqliteodbc/), so we could certainly support that.

**Comment by AndyGreenwell** [comment]
@quinnj, thanks for putting this table together.  Over the course of the next week or two, I will work on building out a couple of machines (using a combination of hard disk partitions and VMs) that could handle each of entries in that matrix, with an initial exception of Teradata on my part.

Eventually automated testing would be ideal, but I will start with manual testing of each configuration.

**Comment by ScottPJones** [comment]
We might be able to do postgres testing, on Linux and Max, but I don't know about windows

**Comment by quinnj** [comment]
Also going to ping @randyzwitch here since I know he's helped test in the past and potentially has access to different DBMS.

**Comment by quinnj** [comment]
In fact, SQLite might be a great way to actually utilize Travis testing. We could make SQLite a dependency of ODBC, include the SQLite ODBC driver by default and have the tests run against it. Not sure if it'd be worth all that efffort if we're going to have a custom test environment anyway, but it just occurred to me that we could.

**Comment by StefanKarpinski** [comment]
Keep in mind that there you can put things in test/REQUIRE to make them test-only dependencies.

**Comment by randyzwitch** [comment]
I can do OSX and Linux for MySQL, Postgres, Teradata, Teradata Aster, and Hortonworks Hive. Just wouldn't be able to do it on a CI basis, since some of them will be hitting live work databases.

I might be able to do Oracle and SQL Server too, I'd just have to poke around a bit and see what access I have :)

**Comment by quinnj** [comment]
Ok, finally have some progress on the `jq/remodel` branch. I'd appreciate any and all testing people are willing to try out as an initial whack. I'm working on building out a more standard test script that anyone could run against a MySQL/SQLite database, but until then, I'd still appreciate some alpha feedback (i.e. any segfaults, obvious bugs) if people want ot try out a couple queries.

To give it a whirl:
```julia
Pkg.checkout("ODBC","jq/remodel")
Pkg.checkout("DataStreams")
using ODBC
dsn = ODBC.DSN("my_dsn")
# or dsn = ODBC.DSN("Drirver={SQL Server}") to provide a full connection string
source = ODBC.Source(dsn, "select * from cool_table")
dt = Data.stream!(source, Data.Table)
```

I've personally tested it on MySQL for windows/OSX and SQL Server on windows which shook out a lot of bugs, but I'm sure there are more.

Next up on the remodel is streaming results directly to a csv file or SQLite table, another thorough review of the API calls to ensure correct typing, a few good robust testing options (DBMS + platform combos), and 0.4 docs. Databases rejoice :)

**Comment by quinnj** [comment]
cc @sglyon as well.

I've made some additional updates as well, so ODBC=>CSV and ODBC=>SQLite should both be working, just make sure to do `Pkg.checkout` on both for now. I'd love to hear if anyone's run into any issues or successes.
