### ISSUE TITLE
Tag a release? 

### ISSUE THREAD

**Issue by aviks** [JuliaDB/ODBC.jl#94]
In particular, https://github.com/quinnj/ODBC.jl/commit/03305ea53d6d4f34ed65f729f9a342c0bb4746de is needed for `advancedconnect` to work. 

cc: @quinnj

**Comment by aviks** [comment]
Bump. 

The last released version (0.3.10) does not work on julia 0.4 at all.

**Comment by quinnj** [comment]
coming soon...

**Comment by tkelman** [comment]
Is this ready to tag? There's an unregistered 0.4.0 tag that should not be pushed to metadata as-is because it's broken on 0.3, but would current master be suitable to tag as 0.4.1 or 0.5.0?

**Comment by ViralBShah** [comment]
I think we should tag master before the new work is merged - just so that while the new thing stabilizes, there is something for existing users of older releases to use.

**Comment by ViralBShah** [comment]
Maybe also have a last release for 0.3 before we move on?

**Comment by quinnj** [comment]
Yes, the plan is to do a final tag for 0.3/0.4, the merge the new redesign and tag a new version for 0.4/0.5.

**Comment by tkelman** [comment]
Anything that needs doing for the former?

**Comment by quinnj** [comment]
I've been working through some older issues trying to make sure we have as much cleaned up as possible, but I think it's probably ready to go.

**Comment by ViralBShah** [comment]
@quinnj I assume you will tag METADATA when ready.

**Comment by quinnj** [comment]
Tagged.
