### ISSUE TITLE
Empty query results from ODBC query on SQLite database

### ISSUE THREAD

**Issue by DataWookie** [JuliaDB/ODBC.jl#96]
Hi,

I have got ODBC connecting to a SQLite database (using SQLiteODBC). Connecting to the DB works fine:

    julia> using DataFrames
    julia> using ODBC
    julia> db = ODBC.connect("passwd")
    ODBC Connection Object
    ----------------------
    Connection Data Source: passwd
    passwd Connection Number: 1
    Contains resultset(s)? No

But when I execute a query I get back an empty result set:

    julia> query("select * from passwd;")
    0x0 DataFrame
    julia> query("select * from passwd;", db)
    0x0 DataFrame

The metadata for the query appears to be fine though:

    julia> querymeta("select * from passwd;")
    Resultset metadata for executed query
    -------------------------------------
    Query:   select * from passwd;
    Columns: 7
    Rows:    0
    7x5 DataFrame
    | Row | Names      | Types                  | Sizes | Digits | Nullable |
    |-----|------------|------------------------|-------|--------|----------|
    | 1   | "username" | ("SQL_LONGVARCHAR",-1) | 65536 | 0      | 1        |
    | 2   | "password" | ("SQL_LONGVARCHAR",-1) | 65536 | 0      | 1        |
    | 3   | "UID"      | ("SQL_DOUBLE",8)       | 54    | 0      | 1        |
    | 4   | "GID"      | ("SQL_DOUBLE",8)       | 54    | 0      | 1        |
    | 5   | "comment"  | ("SQL_LONGVARCHAR",-1) | 65536 | 0      | 1        |
    | 6   | "homedir"  | ("SQL_LONGVARCHAR",-1) | 65536 | 0      | 1        |
    | 7   | "shell"    | ("SQL_LONGVARCHAR",-1) | 65536 | 0      | 1        |

And when I execute the same query using `isql` (for the ODBC interface) or `sqlite3` then I get a ream of results.

Any idea why this might not be working?

Thanks,
Andrew.

**Comment by quinnj** [comment]
Hi @DataWookie, really sorry for never responding on this. I'm currently working on an overhaul of the ODBC package, so I'm going back through issues. If you'd like to still troubleshoot/fix this, just let me know and I'm happy to try and tackle what's going on (I'm actively working on things going forward).

**Comment by DataWookie** [comment]
Hi. Thanks for getting back to me. Yes, that would be great. Please just let me know what you need from me. Thanks, Andrew.

**Comment by quinnj** [comment]
Great! First, let's go straight to the latest code; you can get the package overhaul code by doing the following with any Julia 0.4 release

```julia
Pkg.add("ODBC")
Pkg.checkout("ODBC","jq/remodel")
Pkg.checkout("DataStreams")
Pkg.checkout("CSV")
Pkg.checkout("SQLite")
```
then usage is like:
```julia
using DataStreams, ODBC
# connect to a preconfigured ODBC DSN
conn = ODBC.DSN("[preconfigured_dsn]")
# execute a query until ready to fetch results
source = ODBC.Source(conn, "select * from [some_table]")
# examine the schema of a query; will show the mapped Julia column names/types
source.schema
# show the number of rows/columns the DB is reporting as the result of the query
(source.schema.rows, source.schema.cols)
# show the ODBC types that the DB is reporting for the query
source.schema.metadata
dt = Data.stream!(source, Data.Table)
```
Let me know if you run into any issues here and I'm happy to help debug.

**Comment by quinnj** [comment]
Hey @DataWookie, any update on this? did the new code work for you?

**Comment by DataWookie** [comment]
Thanks, yes, just checked and it seems to have sorted the issue.

**Comment by iamed2** [comment]
I am having this issue but that solution did not work for me. I'll open a new issue.
